//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _54Computer.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public int UrunID { get; set; }
        public string Urun_Adi { get; set; }
        public string Fiyat { get; set; }
        public string Adet { get; set; }
        public string Kategori { get; set; }
    
        public virtual Bilgisayar Bilgisayar { get; set; }
        public virtual Telephone Telephone { get; set; }
    }
}
